// Conference attendance data
export const attendee = [
  {
    conference: "All Things Open",
    location: "Raleigh, NC",
    date: new Date("2025-10-14"),
    description: "Technology conference focusing on the tools, processes and people making open source possible",
    tags: ["Open Source"],
  },
  {
    conference: "CascadiaJS",
    location: "Seattle, WA",
    date: new Date("2025-09-18"),
    description: "Community-driven conference for developers in the PNW and beyond",
    tags: ["Web", "AI"],
  },
  {
    conference: "Laracon US",
    location: "Denver, CO",
    date: new Date("2025-07-30"),
    description: "The flagship Laravel event for Web Artisans",
    tags: ["Laravel", "PHP"],
  },
  {
    conference: "RenderATL",
    location: "Atlanta, GA",
    date: new Date("2025-06-14"),
    description: "The premier conference and expo for tech professionals",
    tags: ["React", "JavaScript", "Web", "AI"],
  },
  {
    conference: "React Miami",
    location: "Miami, FL",
    date: new Date("2025-04-18"),
    description: "The Ultimate React Conference in the US",
    tags: ["React", "JavaScript", "Web", "AI"],
  },
  {
    conference: "All Things Open",
    location: "Raleigh, NC",
    date: new Date("2024-10-14"),
    description: "Technology conference focusing on the tools, processes and people making open source possible",
    tags: ["Open Source"],
  },
  {
    conference: "THAT Conference",
    location: "Wisconsin Dells, WI",
    date: new Date("2024-08-01"),
    description: "A full-stack, tech-obsessed community of fun, code-loving humans who share and learn together",
    tags: ["Full Stack", "Web", "Backend", "Frontend"],
  },
  {
    conference: "Render ATL",
    location: "Atlanta, GA",
    date: new Date("2024-06-14"),
    description: "The premier conference and expo for tech professionals",
    tags: ["React", "JavaScript", "Web", "AI"],
  },
  {
    conference: "THAT Conference",
    location: "Wisconsin Dells, WI",
    date: new Date("2023-07-28"),
    description: "A full-stack, tech-obsessed community of fun, code-loving humans who share and learn together",
    tags: ["Full Stack", "Web", "Backend", "Frontend"],
  },
  {
    conference: "THAT Conference",
    location: "Wisconsin Dells, WI",
    date: new Date("2022-07-28"),
    description: "A full-stack, tech-obsessed community of fun, code-loving humans who share and learn together",
    tags: ["Full Stack", "Web", "Backend", "Frontend"],
  },
  {
    conference: "THAT Conference",
    location: "Wisconsin Dells, WI",
    date: new Date("2019-08-08"),
    description: "A full-stack, tech-obsessed community of fun, code-loving humans who share and learn together",
    tags: ["Full Stack", "Web", "Backend", "Frontend"],
  },
  {
    conference: "THAT Conference",
    location: "Wisconsin Dells, WI",
    date: new Date("2018-08-08"),
    description: "A full-stack, tech-obsessed community of fun, code-loving humans who share and learn together",
    tags: ["Full Stack", "Web", "Backend", "Frontend"],
  },
];
